config/routes.rb
Rails.application.routes.draw do
  resources :maps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'geocode#index'
  get '/geocode' => "geocode#top"
  post '/geocode' => "geocode#search"
  get '/chart' => "chart#top"
  post '/geocode/import' => "geocode#import"
  post '/geocode/s3_upload'  => "geocode#s3_upload"
  get '/geocode/s3_upload'  => "geocode#top"
  get '/geocode/download' => "geocode#download"
  
end

app/controllers/geocode_controller.rb
class GeocodeController < ApplicationController

  def top

  end

  def index

  end

  def search
    @address = params[:address]
    google_map_search(@address)
    render("geocode/top")
  end

  def import
    @import_file = params[:file]
    redirect_to '/geocode' and return unless @import_file
    # csvの読み込みと出力を同時に行う
    csv_data = CSV.generate(headers: true) do |csv|
      csv << csv_attributes

      CSV.foreach(@import_file.path, headers: true) do |row|
        @address = row[0]
        results = google_map_search(@address)
        if results && ['OK', 'already_searched'].include?(results['status'])
          results['results'].each do |result|
            result_data = [
                @address,
                results['status'],
                result['formatted_address'],
                result['types'],
                result['geometry']['location_type']
            ]
            result_data << row[1].presence #請求ID
            result_data << row[2].presence #未着フラグ
            csv << result_data

          end
        else
          result_data = [
              @address,
              results
          ]
          csv << result_data
        end

      end
    end

    # csv出力
    send_data(csv_data, filename: "gmap_result_#{Time.now.strftime("%F")}.csv")

  end

  def s3_upload
    @csv_file = params[:file]
    redirect_to '/geocode' and return unless @csv_file
    s3 = Aws::S3::Resource.new(client: s3_client)
    bucket = s3.bucket(Settings.s3.bucket_name)
    object = bucket.object("uploads/#{@csv_file.original_filename}")
    object.put(body: @csv_file, acl: 'public-read')

    # render("geocode/top")
    redirect_to('/geocode/download')
  end

  # def csv_download
  #   file_name = params[:file]
  #   s3 = Aws::S3::Resource.new(client: s3_client)
  #   object = s3.bucket(Settings.s3.bucket_name).object("uploads/#{file_name}.csv")
  #   if object.present?
  #     send_data object.get.body.read,
  #               filename: "#{file_name}.csv"
  #   else
  #     # ファイルが無いときの処理
  #   end
  #
  # end

  def download
    s3 = Aws::S3::Resource.new(client: s3_client)
    @objects = s3.bucket(Settings.s3.bucket_name).objects(prefix: "processed/")
  end

  # def s3_download
  #     send_data 'hogehoge',
  #               :type => 'text/csv',
  #               :disposition => 'attachment'
  # end
  private

  def csv_attributes
    ["searched_address", "results", "formatted_address", "types", "location_type", "btm_id", "deliverable"]
  end

  def google_map_search(address)
    ActiveRecord::Base.transaction do
      searched_address = SearchedAddress.find_or_initialize_by(address: @address)

      # 検索が初めての住所の場合 -> APIコール
      # すでに検索済の場合 -> 既存の結果を返す
      if searched_address.new_record?
        searched_address.save!

        # API call
        @results = GoogleMapsPlatform::GeocodingApiService.new(@address).call

        #APIのリザルトを処理
        @results['results'].each do |result|

          # save result
          searched_address_response = SearchedAddressResponse.new(
              response: result,
              searched_address: searched_address
          )
          save_with_status(@results['status'], searched_address_response)

          # find_matching_address
          matching_address = FormattedAddress.find_by(address: result['formatted_address'])
          if matching_address
            MatchingAddress.create!(
                searched_address: searched_address,
                formatted_address: matching_address
            )
          else
            formatted_address = FormattedAddress.create!(
                address: result['formatted_address'],
            )
            MatchingAddress.create!(
                searched_address: searched_address,
                formatted_address: formatted_address
            )

          end
        end
      else
        searched_address_responses = SearchedAddressResponse.where(searched_address: searched_address)

        @results = {}
        @results['status'] = 'already_searched'
        @results['results'] = []
        searched_address_responses.each do |response|
          result = eval("#{response.response}")
          @results['results'] << result
        end
      end
    end
    @results
  end

  def save_with_status(status, searched_address_response)
    case status
    when 'OK'
      searched_address_response.ok!
    when 'ZERO_RESULTS'
      searched_address_response.zero_results!
    when 'OVER_DAILY_LIMIT'
      searched_address_response.over_daily_limit!
    when 'OVER_QUERY_LIMIT'
      searched_address_response.over_query_limit!
    when 'REQUEST_DENIED'
      searched_address_response.request_denied!
    when 'INVALID_REQUEST'
      searched_address_response.invalid_request!
    when 'UNKNOWN_ERROR'
      searched_address_response.unknown_error!
    end

    searched_address_response.save!
  end

  def s3_client
    Aws::S3::Client.new(
        access_key_id: ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_KEY_ID'],
        region: 'ap-northeast-1'
    )
  end

end

app/views/geocode/download.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ファイル一覧</title>

  <meta charset="utf-8"/>
</head>
<body class="download">
<h1>結果ファイル</h1>
<p>※右クリック→保存　でダウンロードしてください</p>
<div>
<!--  <tr>-->
<!--    <th>オブジェクト名</th>-->
<!--    <th>url</th>-->
<!--  </tr>-->
<!--  <tr>-->
  <% @objects.each do |item| %>
    <p><%= link_to(item.key.gsub("processed/", ""),item.presigned_url(:get)) %></p>
  <% end %>
<!--  </tr>-->
</div>
</body>
<!--<footer>-->
<!--  <p>&copy; Satoki Yamada. 2020.</p>-->
<!--</footer>-->
</html>

app/views/geocode/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>住所情報取得</title>

  <meta charset="utf-8"/>
</head>
<body class="index">
<div class="index-body">
<div class="button-1">
<!--  <button onclick="location.href='https://get-gmap-data.herokuapp.com/geocode/'">検索する</button>-->
  <a href="https://get-gmap-data.herokuapp.com/geocode/">
    <button type="button">使う</button>
  </a>
</div>
</div>
</body>
<!--<footer>-->
<!--  <p>&copy; Satoki Yamada. 2020.</p>-->
<!--</footer>-->
</html>

app/views/geocode/top.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>住所情報取得</title>
  <!--  <link rel="stylesheet" media="all" href="/assets/application-77c1f0b9f6edb2095e34d8740e9aec6c5b2edcc91b3fa0e29c2e1131cc8f00cf.css">-->
  <meta charset="utf-8"/>
</head>
<body class="top">

<div id="wrapper">
  <div id="header">
    <h1><i class="fa fa-flip-horizontal fa-hand-lizard-o"></i> Google Maps Platformから住所情報を取得する
      <i class="fa fa-hand-lizard-o"></i>
    </h1>
  </div>
  <br>
  <div id="header">
    <h2><i class="fa fa-flip-horizontal fa-hand-lizard-o"></i> 検索フォーム <i class="fa fa-hand-lizard-o"></i>
    </h2>
  </div>
  <div id="contents">
    <div id="form">
      <%= form_tag('/geocode', :method => :post) do %>
        <!--<p><label for="cards">Cards:</label></p>-->
        <p><input type="text" name="address" class="address-input" value="<%= @address %>" placeholder="東京都千代田区麹町~~~">
        </p>
        <p><input type="submit" name="commit" value="Search!!" id="check"></p>
      <% end %>
    </div>
    <% if @results && ['OK', 'already_searched'].include?(@results['status']) %>
      <% @results['results'].each do |result| %>
        <div id="result-table">

          <table border="0.5">
            <tr>
              <th>検索住所</th>
              <td><%= @address %></td>
            </tr>
            <tr>
              <th>処理結果</th>
              <td><%= @results['status'] %></td>
            </tr>
            <tr>
              <th>formatted_address</th>
              <td><%= result['formatted_address'] %></td>
            </tr>
            <tr>
              <th>types</th>
              <td><%= result['types'] %></td>
            </tr>
            <tr>
              <th>location_type</th>
              <td><%= result['geometry']['location_type'] %></td>
            </tr>
            <tr>
              <th>緯度</th>
              <td><%= result['geometry']['location']['lat'] %></td>
            </tr>
            <tr>
              <th>経度</th>
              <td><%= result['geometry']['location']['lng'] %></td>
            </tr>
            <tr>
              <th>partial_match</th>
              <td><%= result['partial_match'] %></td>
            </tr>
          </table>

        </div>
      <% end %>
    <% else %>
      <p><%= @results %></p>
    <% end %>
  </div>
  <br>
  <br>
<!--  <div id="header">-->
<!--    <h2><i class="fa fa-flip-horizontal fa-hand-lizard-o"></i> CSVで一括検索 <i class="fa fa-hand-lizard-o"></i>-->
<!--    </h2>-->
<!--  </div>-->
<!--  <div>-->
    <%#= form_tag geocode_import_path, multipart: true do %>
      <%#= file_field_tag :file %>
      <%#= submit_tag "CSV upload!!" %>
    <%# end %>
<!--  </div>-->
<!--  <br>-->
<!--  <div>※CSVヘッダーは「住所, 数字(integer), boolean(true/false)の形式です。</div>-->

  <%# unless @import_file %>
<!--  <p>ファイルを選択してください</p>-->
  <%# end %>
  <div id="header">
    <h2><i class="fa fa-flip-horizontal fa-hand-lizard-o"></i> CSVで一括検索 <i class="fa fa-hand-lizard-o"></i>
    </h2>
  </div>
  <div>
    <%= form_tag geocode_s3_upload_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "S3 upload!!" %>
    <% end %>
  </div>
  <% unless @csv_file %>
    <p>ファイルを選択してください</p>
  <% end %>
</div>
<br>
<br>
<div>
  <a href="https://developers.google.com/maps/documentation/geocoding/intro">geocoding API公式ガイド</a>
</div>
<div>
  <a href="https://docs.google.com/spreadsheets/d/1EZVB7IQEzBcKvR7uNwR5Pd60ZsKFEfBZUI7VVYKFcyY/edit#gid=695917832">公式ガイドより抜粋</a>
</div>
<br>
</body>
</html>